In [2]:
import numpy as np

In [4]:
np.zeros((2,3)) #cria uma matrix 2(linhas)x3(colunas) de zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,3)) #cria uma matrix identidades recebendo linhas,colunas

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#numpy.arange([start, ]stop, [step, ]dtype=None)
np.arange(10) #retorna valores distribuidos de maneira uniforme dado o intervalo, se start não for dado ele começa do 0, stop é quando ele irá parar e o step é o espaçamento entre valores

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2, 10, dtype=float) #criar um vetor com valores float que irá de 2 à 10(elemento)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
np.arange(2, 3, 0.1) #criar um vetor de 2 a 3 com incrementos de 0.1

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [11]:
np.linspace(1., 4., 6) #cria arrays usando um valor de começo e um de fim e implica a quantidade de steps

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [13]:
np.indices((3,3)) #cria matriz com o indices de cada elemento em linha/coluna

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])